# Generated by Django 3.2.6 on 2021-08-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
