# Generated by Django 3.2.6 on 2021-08-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myaccount_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='show_profile',
            field=models.BooleanField(default=True),
        ),
    ]
