# Generated by Django 3.2.6 on 2021-08-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myaccount_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='job_role',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
