# Generated by Django 3.2.6 on 2021-08-17 13:30

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210815_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='Europe/London'),
        ),
    ]
