# Generated by Django 3.2.6 on 2021-08-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_myaccount_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='events_remaining_in_package',
            field=models.IntegerField(default=1),
        ),
    ]
