# Generated by Django 3.2.6 on 2021-08-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_myaccount_events_remaining_in_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
