# Generated by Django 3.2.6 on 2021-08-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_myaccount_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='myaccount',
            name='industry',
            field=models.CharField(blank=True, default='All', max_length=255),
        ),
    ]
