# Generated by Django 3.2.6 on 2021-09-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210830_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='industry',
            field=models.CharField(blank=True, default='None selected - please complete your profile', max_length=255),
        ),
    ]
