# Generated by Django 3.2.6 on 2021-08-30 23:26

from django.conf import settings
from django.db import migrations, models
import events.models
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=1000)),
                ('header_image', models.ImageField(blank=True, default=events.models.get_default_header_image, null=True, upload_to=events.models.get_header_image_filepath)),
                ('industry', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='Online', max_length=100)),
                ('start_datetime', models.DateTimeField(blank=True, default='', verbose_name='start_date')),
                ('end_datetime', models.DateTimeField(blank=True, default='', verbose_name='end_date')),
                ('timezone', timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='Europe/London')),
                ('max_reg', models.IntegerField(default=100)),
                ('registrants', models.ManyToManyField(blank=True, related_name='attendees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
