# Generated by Django 3.2.6 on 2021-08-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='event_limit',
            field=models.IntegerField(default=1),
        ),
    ]
