# Generated by Django 3.2.5 on 2021-07-10 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        ('checkout', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_purchased',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='packages.package'),
        ),
    ]
