# Generated by Django 3.2.5 on 2021-07-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_stripe_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_pid',
        ),
    ]
